# Generated by Django 5.1.3 on 2026-08-08 12:13

import apps.lab.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingLab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Shown in the lobby before the lab starts.",
                    ),
                ),
                (
                    "join_code",
                    models.CharField(
                        db_index=True,
                        default=apps.lab.models.generate_join_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("running", "Running"),
                            ("review", "Review"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        default=list,
                        help_text="Which languages a student may choose. Empty means all supported.",
                    ),
                ),
                (
                    "allow_late_submissions",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a student may still submit after the lab moves to review.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_labs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lab_coding_labs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabProblemSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=40)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_sets",
                        to="lab.codinglab",
                    ),
                ),
            ],
            options={
                "db_table": "lab_problem_sets",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="LabProblem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                (
                    "statement",
                    models.TextField(
                        help_text="The problem, in prose. Sanitised on write."
                    ),
                ),
                (
                    "starter_code",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="language -> starting source",
                    ),
                ),
                (
                    "reference_solution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The instructor's own solution. Never sent to a student.",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="lab.labproblemset",
                    ),
                ),
            ],
            options={
                "db_table": "lab_problems",
                "ordering": ["problem_set", "order"],
            },
        ),
        migrations.CreateModel(
            name="LabParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("tab_switch_count", models.IntegerField(default=0)),
                ("copy_paste_attempts", models.IntegerField(default=0)),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="lab.codinglab",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned on join. Stored so an instructor override survives.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participants",
                        to="lab.labproblemset",
                    ),
                ),
            ],
            options={
                "db_table": "lab_participants",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="LabSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.TextField()),
                ("student_output", models.TextField(blank=True)),
                ("server_output", models.TextField(blank=True)),
                ("server_stderr", models.TextField(blank=True)),
                ("outputs_match", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Awaiting review"),
                            ("accepted", "Accepted"),
                            ("returned", "Returned for another attempt"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lab.labparticipant",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lab.labproblem",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lab_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codinglab",
            index=models.Index(
                fields=["instructor", "state"], name="lab_coding__instruc_40d611_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="labproblemset",
            constraint=models.UniqueConstraint(
                fields=("lab", "label"), name="lab_unique_set_label"
            ),
        ),
        migrations.AddIndex(
            model_name="labproblem",
            index=models.Index(
                fields=["problem_set", "order"], name="lab_problem_problem_f957d1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="labparticipant",
            constraint=models.UniqueConstraint(
                fields=("lab", "student"), name="lab_one_seat_per_student"
            ),
        ),
        migrations.AddIndex(
            model_name="labsubmission",
            index=models.Index(
                fields=["problem", "status"], name="lab_submiss_problem_37f3aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labsubmission",
            index=models.Index(
                fields=["participant", "problem"], name="lab_submiss_partici_e44c22_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="labsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "accepted")),
                fields=("participant", "problem"),
                name="lab_one_acceptance_per_problem",
            ),
        ),
        migrations.AddConstraint(
            model_name="labsubmission",
            constraint=models.UniqueConstraint(
                fields=("participant", "problem", "attempt_number"),
                name="lab_unique_attempt_number",
            ),
        ),
    ]
