# Generated by Django 4.2.7 on 2025-11-30 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "projects",
            "0003_team_alter_project_description_projectnotification_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
