# Generated by Django 4.2.7 on 2025-11-10 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_mentor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("openai", "OpenAI GPT"),
                            ("anthropic", "Anthropic Claude"),
                            ("cohere", "Cohere"),
                            ("huggingface", "HuggingFace"),
                            ("custom", "Custom Model"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Model ID like gpt-4, gemini-pro, etc.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("coming_soon", "Coming Soon"),
                            ("disabled", "Disabled"),
                        ],
                        default="coming_soon",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🤖", help_text="Emoji or icon", max_length=10
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserAISettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("openai_api_key", models.CharField(blank=True, max_length=200)),
                ("anthropic_api_key", models.CharField(blank=True, max_length=200)),
                ("cohere_api_key", models.CharField(blank=True, max_length=200)),
                ("huggingface_api_key", models.CharField(blank=True, max_length=200)),
                ("custom_api_keys", models.JSONField(blank=True, default=dict)),
                ("temperature", models.FloatField(default=0.7, help_text="0.0 to 1.0")),
                ("max_tokens", models.IntegerField(default=2000)),
                ("stream_responses", models.BooleanField(default=False)),
                ("save_history", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="ai_mentor.aimodelconfig",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomAIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("endpoint_url", models.URLField()),
                ("api_key", models.CharField(max_length=500)),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "request_format",
                    models.JSONField(
                        default=dict, help_text="Request body format with placeholders"
                    ),
                ),
                (
                    "response_path",
                    models.CharField(
                        default="response",
                        help_text="Path to response text in JSON",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_ai_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
    ]
