# Generated by Django 4.2.7 on 2025-12-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mentor", "0002_aimodelconfig_useraisettings_customaimodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmentorsession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated title from first message",
                max_length=255,
                null=True,
            ),
        ),
    ]
