# Generated by Django 5.1.3 on 2025-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mentor", "0003_add_title_to_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimentorprofile",
            name="preferred_ai_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openrouter_gemini", "Gemini 2.0 Flash (OpenRouter)"),
                    ("openrouter_amazon_nova", "Amazon Nova 2 Lite"),
                    ("openrouter_deepseek", "DeepSeek V3.1 NEX"),
                    ("openrouter_mistral", "Mistral Devstral"),
                    ("google_gemini", "Google Gemini (Direct)"),
                    ("openai_gpt4", "OpenAI GPT-4"),
                    ("anthropic_claude", "Anthropic Claude"),
                    ("openrouter", "OpenRouter (Legacy)"),
                    ("local", "Local AI"),
                ],
                help_text="User must select a model",
                max_length=30,
                null=True,
            ),
        ),
    ]
