# Generated by Django 4.2.7 on 2026-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_mentor", "0004_add_openrouter_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimentorprofile",
            name="preferred_ai_model",
            field=models.CharField(
                blank=True,
                help_text="User must select a model",
                max_length=100,
                null=True,
            ),
        ),
    ]
