# Generated by Django 5.1.3 on 2026-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mentor", "0005_expand_preferred_ai_model_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimentorprofile",
            name="preferred_ai_model",
            field=models.CharField(
                blank=True,
                default="mistral_direct",
                help_text="User must select a model",
                max_length=100,
            ),
        ),
    ]
