# Generated by Django 4.2.7 on 2026-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mentor", "0006_set_default_mistral_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraisettings",
            name="gemini_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="useraisettings",
            name="mistral_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="useraisettings",
            name="openrouter_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
