# Generated by Django 4.2.7 on 2025-11-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_add_chat_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="accepted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
