# Generated by Django 5.1.3 on 2026-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_add_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('question', 'Question'), ('showcase', 'Showcase'), ('tutorial', 'Tutorial'), ('discussion', 'Discussion')], default='text', max_length=20),
        ),
    ]
