# Generated by Django 4.2.7 on 2026-07-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_add_image_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("project_invite", "Project Invite"),
                    ("badge_earned", "Badge Earned"),
                    ("course_completed", "Course Completed"),
                    ("review_request", "Review Request"),
                    ("announcement", "Announcement"),
                    ("org_join_request", "Organization Join Request"),
                    ("org_invitation", "Organization Invitation"),
                    ("org_approved", "Organization Approved"),
                ],
                max_length=20,
            ),
        ),
    ]
