# Generated by Django 4.2.7 on 2026-07-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-is_pinned", "-created_at"], name="post_feed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["post_type", "-created_at"], name="post_type_feed_idx"
            ),
        ),
    ]
