# Generated by Django 5.1.3 on 2026-08-04 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_post_post_feed_idx_post_post_type_feed_idx"),
        ("projects", "0004_add_task_dates_and_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("muted", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="chatroom",
            options={"ordering": ["scope", "room_type", "name"]},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="last_reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="thread_root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_replies",
                to="community.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="community.organization",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="scope",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("organization", "Organization"),
                    ("project", "Project"),
                    ("task", "Task"),
                ],
                db_index=True,
                default="global",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="projects.projecttask",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("IT", "Information Technology"),
                    ("IS", "Information Systems"),
                    ("GLOBAL", "Global Chat"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "thread_root", "created_at"],
                name="chatmsg_room_thread_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "global")),
                fields=("room_type",),
                name="chatroom_one_room_per_program",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "organization")),
                fields=("organization",),
                name="chatroom_one_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "project")),
                fields=("project",),
                name="chatroom_one_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "task")),
                fields=("task",),
                name="chatroom_one_per_task",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            # `check=`, not `condition=`. makemigrations wrote `condition=` because
            # this machine has Django 5.1; production runs the pinned 4.2.7, where
            # CheckConstraint has no `condition` kwarg and this migration would
            # fail on deploy. Do not "fix" the deprecation warning 5.1 emits for
            # this until requirements.txt actually moves off 4.2.
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("organization__isnull", True),
                        ("project__isnull", True),
                        ("scope", "global"),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("organization__isnull", False),
                        ("project__isnull", True),
                        ("scope", "organization"),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("organization__isnull", True),
                        ("project__isnull", False),
                        ("scope", "project"),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("organization__isnull", True),
                        ("project__isnull", True),
                        ("scope", "task"),
                        ("task__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chatroom_scope_matches_target",
            ),
        ),
        migrations.AddField(
            model_name="channelmembership",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="community.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="channelmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(fields=["user", "channel"], name="chanmember_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="channelmembership",
            constraint=models.UniqueConstraint(
                fields=("channel", "user"), name="channelmembership_unique"
            ),
        ),
    ]
