# Generated by Django 4.2.7 on 2026-08-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0009_channelmembership_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("task_created", "Task created"),
                    ("task_assigned", "Task assigned"),
                    ("task_status", "Task status changed"),
                ],
                db_index=True,
                default="",
                max_length=24,
            ),
        ),
    ]
