# Generated by Django 4.2.7 on 2026-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0010_chatmessage_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
