# Generated by Django 4.2.7 on 2026-08-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0011_post_comments_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
