# Generated by Django 4.2.7 on 2025-11-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("bsit", "BS Information Technology"),
                            ("bscs", "BS Computer Science"),
                            ("bsis", "BS Information Systems"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Duration in weeks (1-52)"),
                ),
                ("total_modules", models.IntegerField(default=0)),
                ("points_reward", models.IntegerField(default=100)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("icon", models.URLField(blank=True, null=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(blank=True, to="learning.careerpath"),
                ),
            ],
            options={
                "ordering": ["program_type", "difficulty_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="LearningModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("text", "Text"),
                            ("interactive", "Interactive"),
                            ("quiz", "Quiz"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="For text content or video URL"),
                ),
                ("duration_minutes", models.IntegerField(default=30)),
                ("points_reward", models.IntegerField(default=10)),
                (
                    "order",
                    models.IntegerField(help_text="Order within the career path"),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "career_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="learning.careerpath",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(blank=True, to="learning.learningmodule"),
                ),
            ],
            options={
                "ordering": ["career_path", "order"],
                "unique_together": {("career_path", "order")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("coding", "Coding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("correct_answer", models.JSONField()),
                ("points", models.IntegerField(default=1)),
                ("order", models.IntegerField(default=0)),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Shown after answer"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("time_limit_minutes", models.IntegerField(default=30)),
                (
                    "passing_score",
                    models.IntegerField(default=70, help_text="Percentage"),
                ),
                ("max_attempts", models.IntegerField(default=3)),
                ("randomize_questions", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learning_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="learning.learningmodule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("time_taken_seconds", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("timed_out", "Timed Out"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="learning.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("choice_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="learning.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="learning.quiz",
            ),
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completion_percentage", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "career_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.careerpath",
                    ),
                ),
                (
                    "learning_module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.learningmodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_accessed_at"],
                "unique_together": {("user", "career_path", "learning_module")},
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_id", models.CharField(max_length=100, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_url", models.URLField(blank=True, null=True)),
                (
                    "career_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.careerpath",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "career_path")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_data", models.JSONField()),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.question",
                    ),
                ),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="learning.quizattempt",
                    ),
                ),
            ],
            options={
                "unique_together": {("quiz_attempt", "question")},
            },
        ),
    ]
