# Generated by Django 5.1.3 on 2025-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerpath",
            name="certificate_template",
            field=models.FileField(
                blank=True,
                help_text="Certificate template for course completion",
                null=True,
                upload_to="certificates/templates/",
            ),
        ),
    ]
