# Generated by Django 5.1.3 on 2025-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_enrollment_certificate_enrollment_moduleprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmodule",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload module file (PDF, DOCX, etc.)",
                null=True,
                upload_to="module_files/",
            ),
        ),
    ]
