# Generated by Django 5.1.3 on 2025-11-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_learningmodule_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="current_slide",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="total_slides",
            field=models.IntegerField(default=1),
        ),
    ]
