# Generated by Django 5.1.3 on 2025-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_userprogress_current_slide_userprogress_total_slides"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerpath",
            name="max_modules",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of modules for this path (0 = unlimited)",
            ),
        ),
    ]
