# Generated by Django 4.2.7 on 2025-12-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_quiz_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerpath",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("bsit", "BS Information Technology"),
                    ("bscs", "BS Computer Science"),
                    ("bsis", "BS Information Systems"),
                    ("general", "General"),
                ],
                max_length=10,
            ),
        ),
    ]
