# Generated by Django 4.2.7 on 2026-01-29 07:12

import apps.learning.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0008_alter_careerpath_program_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveQuiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "creation_method",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Upload"),
                            ("ai_prompt", "AI Generated"),
                            ("manual", "Manual Entry"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True, null=True, upload_to="live_quiz_sources/"
                    ),
                ),
                ("ai_prompt_text", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "join_code",
                    models.CharField(
                        db_index=True,
                        default=apps.learning.models.generate_join_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("auto_advance_questions", models.BooleanField(default=True)),
                ("show_leaderboard", models.BooleanField(default=True)),
                ("show_correct_answers", models.BooleanField(default=True)),
                ("allow_late_join", models.BooleanField(default=False)),
                ("shuffle_questions", models.BooleanField(default=False)),
                ("shuffle_answers", models.BooleanField(default=True)),
                ("require_fullscreen", models.BooleanField(default=True)),
                ("auto_pause_on_exit", models.BooleanField(default=True)),
                (
                    "max_violations",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "violation_penalty_points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "default_question_time",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "break_between_questions",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "live_quiz",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveQuizParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("total_score", models.IntegerField(db_index=True, default=0)),
                ("total_correct", models.IntegerField(default=0)),
                ("total_attempted", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("rank", models.IntegerField(blank=True, db_index=True, null=True)),
                ("fullscreen_violations", models.IntegerField(default=0)),
                ("tab_switch_count", models.IntegerField(default=0)),
                ("copy_paste_attempts", models.IntegerField(default=0)),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                ("is_paused", models.BooleanField(default=False)),
                ("pause_reason", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("websocket_id", models.CharField(blank=True, max_length=100)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "live_quiz_participant",
                "ordering": ["-total_score", "average_response_time"],
            },
        ),
        migrations.CreateModel(
            name="LiveQuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("coding", "Coding Challenge"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(db_index=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("option_a", models.CharField(blank=True, max_length=500)),
                ("option_b", models.CharField(blank=True, max_length=500)),
                ("option_c", models.CharField(blank=True, max_length=500)),
                ("option_d", models.CharField(blank=True, max_length=500)),
                ("correct_answer", models.CharField(max_length=500)),
                ("explanation", models.TextField(blank=True)),
                (
                    "programming_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("python", "Python 3"),
                            ("javascript", "JavaScript (Node.js)"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                        ],
                        max_length=50,
                    ),
                ),
                ("starter_code", models.TextField(blank=True)),
                ("test_cases", models.JSONField(blank=True, default=list)),
                ("solution_code", models.TextField(blank=True)),
                (
                    "points",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                ("time_bonus_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_questions",
                        to="learning.livequiz",
                    ),
                ),
            ],
            options={
                "db_table": "live_quiz_question",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LiveQuizSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Waiting to Start"),
                            ("in_progress", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Completed"),
                        ],
                        db_index=True,
                        default="lobby",
                        max_length=20,
                    ),
                ),
                (
                    "current_question_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("total_participants", models.IntegerField(default=0)),
                ("active_participants", models.IntegerField(default=0)),
                ("total_questions_shown", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_sessions",
                        to="learning.livequizquestion",
                    ),
                ),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="learning.livequiz",
                    ),
                ),
            ],
            options={
                "db_table": "live_quiz_session",
            },
        ),
        migrations.CreateModel(
            name="LiveQuizResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.CharField(blank=True, max_length=500)),
                ("code_submission", models.TextField(blank=True)),
                ("test_results", models.JSONField(blank=True, default=dict)),
                ("is_correct", models.BooleanField()),
                ("points_earned", models.IntegerField(default=0)),
                ("response_time_seconds", models.FloatField()),
                ("answered_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_responses",
                        to="learning.livequizparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_responses",
                        to="learning.livequizquestion",
                    ),
                ),
            ],
            options={
                "db_table": "live_quiz_response",
            },
        ),
        migrations.AddField(
            model_name="livequizparticipant",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="learning.livequizsession",
            ),
        ),
        migrations.AddField(
            model_name="livequizparticipant",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_quiz_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="livequizsession",
            index=models.Index(
                fields=["status", "-created_at"], name="live_quiz_s_status_ae4091_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livequizresponse",
            index=models.Index(
                fields=["participant", "answered_at"],
                name="live_quiz_r_partici_d9083e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="livequizresponse",
            index=models.Index(
                fields=["question", "is_correct"], name="live_quiz_r_questio_f3ae66_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="livequizresponse",
            unique_together={("participant", "question")},
        ),
        migrations.AddIndex(
            model_name="livequizquestion",
            index=models.Index(
                fields=["quiz", "order"], name="live_quiz_q_quiz_id_7098d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="livequizquestion",
            unique_together={("quiz", "order")},
        ),
        migrations.AddIndex(
            model_name="livequizparticipant",
            index=models.Index(
                fields=["session", "-total_score"],
                name="live_quiz_p_session_db344b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="livequizparticipant",
            index=models.Index(
                fields=["session", "is_active"], name="live_quiz_p_session_e5778c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="livequizparticipant",
            unique_together={("session", "student")},
        ),
        migrations.AddIndex(
            model_name="livequiz",
            index=models.Index(
                fields=["instructor", "-created_at"],
                name="live_quiz_instruc_b7ab25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="livequiz",
            index=models.Index(
                fields=["is_active", "started_at"], name="live_quiz_is_acti_846343_idx"
            ),
        ),
    ]
