# Generated by Django 4.2.7 on 2026-01-29 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0009_livequiz_livequizparticipant_livequizquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livequiz",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When quiz closes (null = no deadline)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="livequiz",
            name="max_retakes",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Max attempts per student (0 = unlimited)",
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AddField(
            model_name="livequiz",
            name="scheduled_start",
            field=models.DateTimeField(
                blank=True,
                help_text="When quiz becomes available (null = immediately)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="livequiz",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total time to complete quiz (null = no limit)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(480),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="livequiz",
            index=models.Index(
                fields=["deadline"], name="live_quiz_deadlin_2ef818_idx"
            ),
        ),
    ]
