# Generated by Django 4.2.7 on 2026-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0011_anticheat_actions_and_feature_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="livequiz",
            name="quiz_mode",
            field=models.CharField(
                choices=[
                    ("live", "Live (Host Required)"),
                    ("self_paced", "Self-Paced (Deadline)"),
                ],
                db_index=True,
                default="live",
                max_length=20,
            ),
        ),
    ]
