# Generated by Django 5.1.3 on 2026-03-17 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0012_add_quiz_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Problem statement in Markdown"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basics", "Basics"),
                            ("arrays", "Arrays & Lists"),
                            ("strings", "Strings"),
                            ("math", "Math & Logic"),
                            ("sorting", "Sorting & Searching"),
                            ("linked_lists", "Linked Lists"),
                            ("trees", "Trees & Graphs"),
                            ("dp", "Dynamic Programming"),
                            ("oop", "Object-Oriented"),
                            ("web", "Web Development"),
                            ("database", "Database & SQL"),
                            ("algorithms", "Algorithms"),
                        ],
                        default="basics",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["recursion", "binary-search"]',
                    ),
                ),
                (
                    "supported_languages",
                    models.JSONField(
                        default=list,
                        help_text='e.g. ["python", "javascript", "java", "cpp"]',
                    ),
                ),
                (
                    "starter_code",
                    models.JSONField(
                        default=dict,
                        help_text='Per-language starter code: {"python": "def solve(n):\\n    pass", ...}',
                    ),
                ),
                (
                    "solution_code",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reference solutions (hidden from students)",
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        default=list,
                        help_text='[{"input": "5\\n3", "expected_output": "8", "is_hidden": false}, ...]',
                    ),
                ),
                (
                    "constraints",
                    models.TextField(blank=True, help_text="Time/space constraints"),
                ),
                ("hints", models.JSONField(blank=True, default=list)),
                ("points", models.IntegerField(default=10)),
                (
                    "time_limit_seconds",
                    models.IntegerField(
                        default=300, help_text="Max solve time in seconds"
                    ),
                ),
                ("total_attempts", models.IntegerField(default=0)),
                ("total_solved", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["difficulty", "category", "title"],
            },
        ),
        migrations.CreateModel(
            name="CodingSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=20)),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("partial", "Partial"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("passed_tests", models.IntegerField(default=0)),
                ("total_tests", models.IntegerField(default=0)),
                ("results_json", models.JSONField(blank=True, default=list)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("points_earned", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="learning.codingchallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("description", models.TextField()),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, help_text="Course thumbnail image URL"),
                ),
                (
                    "instructor_name",
                    models.CharField(
                        help_text='e.g. "freeCodeCamp", "Traversy Media"',
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web_dev", "Web Development"),
                            ("mobile", "Mobile Development"),
                            ("data_science", "Data Science"),
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("cpp", "C/C++"),
                            ("devops", "DevOps"),
                            ("database", "Database"),
                            ("algorithms", "Algorithms"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("total_duration_minutes", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_video_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("video_url", models.URLField(help_text="YouTube or Vimeo URL")),
                ("duration_minutes", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                (
                    "is_free",
                    models.BooleanField(
                        default=True,
                        help_text="Preview lesson (accessible without enrollment)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning.videocourse",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("watched_seconds", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="learning.videolesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_watched_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["difficulty", "category"], name="learning_co_difficu_20a8d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingchallenge",
            index=models.Index(
                fields=["is_active", "difficulty"],
                name="learning_co_is_acti_134b42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codingsubmission",
            index=models.Index(
                fields=["user", "challenge", "status"],
                name="learning_co_user_id_d2c7bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codingsubmission",
            index=models.Index(
                fields=["challenge", "status"], name="learning_co_challen_ca6085_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videolesson",
            unique_together={("course", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="videoprogress",
            unique_together={("user", "lesson")},
        ),
    ]
