# Generated by Django 4.2.7 on 2026-04-30 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0016_achieved_skills_and_skills_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="achievedskill",
            name="unique_skill_per_source",
        ),
        migrations.AlterUniqueTogether(
            name="achievedskill",
            unique_together={("user", "skill_name", "source_type", "source_id")},
        ),
    ]
