# Generated by Django 4.2.7 on 2026-04-30 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0017_achieved_skills_and_skills_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=300)),
                ("icon", models.CharField(default="🏅", max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coding", "Coding"),
                            ("learning", "Learning"),
                            ("quiz", "Quiz"),
                            ("community", "Community"),
                            ("streak", "Streak"),
                            ("milestone", "Milestone"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("challenges_solved", "Coding Challenges Solved"),
                            ("challenges_solved_fast", "Challenge Solved Under 60s"),
                            ("paths_completed", "Career Paths Completed"),
                            ("modules_completed", "Modules Completed"),
                            ("certificates_earned", "Certificates Earned"),
                            ("quiz_perfect", "Quiz Score 100%"),
                            ("streak_days", "Consecutive Active Days"),
                            ("community_upvotes", "Community Post Upvotes"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "trigger_threshold",
                    models.IntegerField(
                        default=1, help_text="How many of trigger_type needed"
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "trigger_threshold"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("context_note", models.CharField(blank=True, max_length=200)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earners",
                        to="learning.badgedefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
