# Generated by Django 4.2.7 on 2026-04-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0018_badge_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(db_index=True, default=0)),
                ("weekly_points", models.IntegerField(db_index=True, default=0)),
                ("monthly_points", models.IntegerField(db_index=True, default=0)),
                ("modules_completed", models.IntegerField(default=0)),
                ("challenges_solved", models.IntegerField(default=0)),
                ("paths_completed", models.IntegerField(default=0)),
                ("certificates_earned", models.IntegerField(default=0)),
                ("badges_earned", models.IntegerField(default=0)),
                ("quiz_perfect_scores", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_points"],
            },
        ),
    ]
