# Generated by Django 5.1.3 on 2026-08-04 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0024_shorten_certificate_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("bsit", "BS Information Technology"),
                            ("bscs", "BS Computer Science"),
                            ("bsis", "BS Information Systems"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="One or two sentences, shown on the card"
                    ),
                ),
                (
                    "core_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Short skill names shown as chips. Keep to about five.",
                    ),
                ),
                (
                    "demand",
                    models.CharField(
                        choices=[
                            ("high", "High demand"),
                            ("steady", "Steady demand"),
                            ("emerging", "Emerging"),
                        ],
                        default="steady",
                        max_length=10,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Within its category"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["program_type", "category", "order", "name"],
            },
        ),
        # makemigrations also wanted a RenameIndex on jobcache and an AlterField
        # on savedjob.id here. Both are pre-existing drift between the learning
        # models and their migrations, unrelated to CareerRole, and earlier
        # migrations in this app were hand-written to leave them alone. Bundling
        # someone else's unreviewed schema change into a feature migration is how
        # a deploy fails for a reason nobody can connect to the change. They stay
        # out; the drift is tracked separately.
        migrations.AddField(
            model_name="careerrole",
            name="career_path",
            field=models.ForeignKey(
                blank=True,
                help_text="The learning path that prepares for this role, once seeded",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="career_roles",
                to="learning.careerpath",
            ),
        ),
        migrations.AddIndex(
            model_name="careerrole",
            index=models.Index(
                fields=["program_type", "category"], name="careerrole_program_cat_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="careerrole",
            constraint=models.UniqueConstraint(
                fields=("program_type", "name"), name="careerrole_unique_per_program"
            ),
        ),
    ]
