# Generated by Django 4.2.7 on 2025-11-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="career_interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="program",
            field=models.CharField(
                choices=[
                    ("BSIT", "BS Information Technology"),
                    ("BSCS", "BS Computer Science"),
                    ("BSIS", "BS Information Systems"),
                ],
                default="BSIT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="year_level",
            field=models.CharField(
                choices=[
                    ("1", "1st Year"),
                    ("2", "2nd Year"),
                    ("3", "3rd Year"),
                    ("4", "4th Year"),
                ],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="certificates_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contribution_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_likes_received",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_modules_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("auto", "Auto")],
                default="dark",
                max_length=20,
            ),
        ),
    ]
