# Generated by Django 4.2.7 on 2025-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_background",
            field=models.CharField(
                choices=[
                    ("hyperspeed", "Hyperspeed"),
                    ("akira", "Akira"),
                    ("golden", "Golden"),
                    ("split", "Split"),
                    ("highway", "Highway"),
                    ("gradient", "Classic"),
                    ("aurora", "Aurora"),
                    ("cyber", "Cyber"),
                ],
                default="gradient",
                max_length=20,
            ),
        ),
    ]
