# Generated by Django 4.2.7 on 2026-01-27 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_google_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_ai_mentor",
                    models.BooleanField(
                        default=True, help_text="Enable AI Mentor feature"
                    ),
                ),
                (
                    "enable_code_editor",
                    models.BooleanField(default=True, help_text="Enable code editor"),
                ),
                (
                    "enable_competitions",
                    models.BooleanField(default=True, help_text="Enable competitions"),
                ),
                (
                    "enable_projects",
                    models.BooleanField(default=True, help_text="Enable projects"),
                ),
                (
                    "enable_community",
                    models.BooleanField(
                        default=True, help_text="Enable community features"
                    ),
                ),
                (
                    "enable_learning_paths",
                    models.BooleanField(
                        default=True, help_text="Enable learning paths"
                    ),
                ),
                (
                    "enable_analytics",
                    models.BooleanField(
                        default=False, help_text="Enable analytics (admin only)"
                    ),
                ),
                (
                    "enable_user_delete",
                    models.BooleanField(
                        default=False, help_text="Allow admins to delete users"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
                "db_table": "app_settings",
            },
        ),
    ]
