# Generated by Django 4.2.7 on 2025-11-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("problem_statement", models.TextField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("algorithm", "Algorithm"),
                            ("data_structure", "Data Structure"),
                            ("debugging", "Debugging"),
                            ("optimization", "Optimization"),
                            ("system_design", "System Design"),
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("fullstack", "Full Stack"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.IntegerField(default=100)),
                ("time_limit", models.IntegerField(help_text="Time limit in minutes")),
                ("memory_limit", models.IntegerField(help_text="Memory limit in MB")),
                ("input_format", models.TextField()),
                ("output_format", models.TextField()),
                ("constraints", models.TextField()),
                ("sample_input", models.TextField()),
                ("sample_output", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("hidden_test_cases", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["competition", "points"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("rules", models.TextField()),
                ("prize_description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
                ("max_participants", models.IntegerField(default=100)),
                ("current_participants", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_data", models.TextField()),
                ("expected_output", models.TextField()),
                ("is_hidden", models.BooleanField(default=True)),
                ("points", models.IntegerField(default=10)),
                ("time_limit", models.IntegerField(help_text="Time limit in seconds")),
                ("memory_limit", models.IntegerField(help_text="Memory limit in MB")),
                ("order", models.IntegerField(default=0)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="competitions.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["challenge", "order"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("csharp", "C#"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("time_limit", "Time Limit Exceeded"),
                            ("memory_limit", "Memory Limit Exceeded"),
                            ("runtime_error", "Runtime Error"),
                            ("compile_error", "Compilation Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "execution_time",
                    models.IntegerField(default=0, help_text="In milliseconds"),
                ),
                ("memory_used", models.IntegerField(default=0, help_text="In KB")),
                ("test_cases_passed", models.IntegerField(default=0)),
                ("total_test_cases", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="competitions.challenge",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="competitions.competition",
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_solve", "First to Solve"),
                            ("fastest_solve", "Fastest Solution"),
                            ("most_efficient", "Most Efficient"),
                            ("perfect_score", "Perfect Score"),
                            ("participation", "Participation"),
                            ("winner", "Competition Winner"),
                            ("runner_up", "Runner Up"),
                            ("top_10", "Top 10 Finish"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("points_awarded", models.IntegerField(default=0)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.challenge",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("challenges_solved", models.IntegerField(default=0)),
                (
                    "total_time",
                    models.IntegerField(default=0, help_text="Total time in minutes"),
                ),
                ("rank", models.IntegerField(default=0)),
                ("last_submission", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="competitions.competition",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_score", "total_time"],
                "unique_together": {("competition", "participant")},
            },
        ),
        migrations.CreateModel(
            name="CompetitionRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="competitions.competition",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["registered_at"],
                "unique_together": {("competition", "participant")},
            },
        ),
    ]
